name: Python

on:
  push:
    branches:
    - master
    workflow_dispatch:

jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run
        run: |
          python translater.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
