name: Spider

on:
  workflow_dispatch:
  #schedule:
    #- cron:  '0 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Rplace
        run: |
          pip install requests
          python downloader.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "更新原脚本" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
